# Generated by Django 3.1.4 on 2020-12-01 20:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='avatar',
        ),
        migrations.RemoveField(
            model_name='user',
            name='current_os',
        ),
        migrations.DeleteModel(
            name='OS',
        ),
        migrations.DeleteModel(
            name='Permiss',
        ),
        migrations.DeleteModel(
            name='User',
        ),
    ]
