# Generated by Django 3.1.3 on 2020-11-18 18:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='OS',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Название OC')),
                ('html_text', models.TextField(verbose_name='HTML текст')),
                ('config', models.CharField(max_length=255, verbose_name='Конфиг')),
                ('ssh_enable', models.BooleanField(default=False, verbose_name='SSH активирован')),
                ('vnc_enable', models.BooleanField(default=False, verbose_name='VNC активирован')),
            ],
            options={
                'verbose_name': 'ОС',
                'verbose_name_plural': 'ОС',
            },
        ),
        migrations.CreateModel(
            name='Permiss',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('livetime', models.DateTimeField(verbose_name='Время жизни')),
            ],
            options={
                'verbose_name': 'Права',
                'verbose_name_plural': 'Права',
            },
        ),
        migrations.CreateModel(
            name='Photos',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('path', models.CharField(max_length=100, verbose_name='Путь')),
            ],
            options={
                'verbose_name': 'Фото',
                'verbose_name_plural': 'Фото',
            },
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('login', models.CharField(max_length=100, verbose_name='Логин')),
                ('password', models.CharField(max_length=100, verbose_name='Пороль')),
                ('is_admin', models.BooleanField(verbose_name='Админ')),
                ('avatar', models.OneToOneField(null=True, on_delete=django.db.models.deletion.SET_NULL, to='database.photos', verbose_name='Аватар')),
                ('current_os', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='database.os', verbose_name='Текущая ОС')),
            ],
            options={
                'verbose_name': 'Пользователь',
                'verbose_name_plural': 'Пользователи',
            },
        ),
        migrations.AddField(
            model_name='os',
            name='permission',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.SET_NULL, to='database.permiss', verbose_name='Права'),
        ),
        migrations.AddField(
            model_name='os',
            name='photos',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='database.photos', verbose_name='Фото'),
        ),
    ]
