# Generated by Django 3.1.4 on 2020-12-01 20:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('core', '0002_auto_20201201_2323'),
    ]

    operations = [
        migrations.CreateModel(
            name='Permiss',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('livetime', models.DateTimeField(verbose_name='Время жизни')),
            ],
            options={
                'verbose_name': 'Права',
                'verbose_name_plural': 'Права',
            },
        ),
        migrations.CreateModel(
            name='OS',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=500, verbose_name='Название OC')),
                ('html_text', models.TextField(verbose_name='HTML текст')),
                ('config', models.CharField(max_length=50000, verbose_name='Конфиг')),
                ('ssh_enable', models.BooleanField(default=False, verbose_name='SSH активирован')),
                ('vnc_enable', models.BooleanField(default=False, verbose_name='VNC активирован')),
                ('is_active', models.BooleanField(default=True, verbose_name='Активна')),
                ('permission', models.OneToOneField(null=True, on_delete=django.db.models.deletion.SET_NULL, to='os_api.permiss', verbose_name='Права')),
                ('photos', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.photos', verbose_name='Фото')),
            ],
            options={
                'verbose_name': 'ОС',
                'verbose_name_plural': 'ОС',
            },
        ),
    ]
