# Generated by Django 3.1.4 on 2020-12-01 20:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('os_api', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='permiss',
            old_name='livetime',
            new_name='live_time',
        ),
    ]
