# Generated by Django 3.1.4 on 2020-12-01 21:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('os_api', '0002_auto_20201201_2352'),
    ]

    operations = [
        migrations.AlterField(
            model_name='os',
            name='config',
            field=models.TextField(max_length=50000, verbose_name='Конфиг'),
        ),
    ]
