# Generated by Django 3.1.4 on 2020-12-01 21:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('os_api', '0003_auto_20201202_0023'),
    ]

    operations = [
        migrations.AlterField(
            model_name='os',
            name='config',
            field=models.TextField(max_length=50000, null=True, verbose_name='Конфиг'),
        ),
    ]
