# Generated by Django 3.1.4 on 2020-12-01 21:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_auto_20201201_2323'),
        ('os_api', '0004_auto_20201202_0027'),
    ]

    operations = [
        migrations.AlterField(
            model_name='os',
            name='config',
            field=models.TextField(blank=True, max_length=50000, null=True, verbose_name='Конфиг'),
        ),
        migrations.AlterField(
            model_name='os',
            name='permission',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='os_api.permiss', verbose_name='Права'),
        ),
        migrations.AlterField(
            model_name='os',
            name='photos',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.photos', verbose_name='Фото'),
        ),
    ]
