# Generated by Django 3.1.4 on 2020-12-01 22:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('os_api', '0006_os_version'),
    ]

    operations = [
        migrations.AddField(
            model_name='os',
            name='vendor',
            field=models.TextField(blank=True, null=True, verbose_name='Создатель ОС'),
        ),
    ]
