# Generated by Django 3.1.4 on 2020-12-04 23:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('os_api', '0008_auto_20201202_0121'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='os',
            name='config',
        ),
        migrations.AddField(
            model_name='os',
            name='emulation_type',
            field=models.IntegerField(choices=[(-1, 'No'), (1, 'Qemu Kvm')], default=-1, verbose_name='Тип эмуляции'),
        ),
        migrations.AddField(
            model_name='os',
            name='start_config',
            field=models.TextField(blank=True, max_length=50000, null=True, verbose_name='Конфигурация запуска'),
        ),
        migrations.AddField(
            model_name='os',
            name='stop_config',
            field=models.TextField(blank=True, max_length=50000, null=True, verbose_name='Конфигурация остановки'),
        ),
        migrations.AlterField(
            model_name='os',
            name='permission',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to='os_api.permiss', verbose_name='Права'),
        ),
    ]
