# Generated by Django 3.1.4 on 2020-12-05 00:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('os_api', '0010_auto_20201205_0232'),
    ]

    operations = [
        migrations.AddField(
            model_name='os',
            name='ssh_type',
            field=models.IntegerField(choices=[(1, 'Ssh'), (2, 'Raw Console')], null=True, verbose_name='Тип консольного подключения'),
        ),
    ]
