# Generated by Django 3.1.4 on 2021-05-16 15:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('os_api', '0012_os_wait_time'),
    ]

    operations = [
        migrations.AddField(
            model_name='os',
            name='additional_info',
            field=models.TextField(blank=True, max_length=50000, null=True, verbose_name='Дополнительная информация при запуске'),
        ),
    ]
