# Generated by Django 3.1.4 on 2020-12-01 20:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('os_api', '0001_initial'),
        ('core', '0002_auto_20201201_2323'),
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('email', models.EmailField(max_length=254, unique=True, verbose_name='Email')),
                ('is_staff', models.BooleanField(default=False, verbose_name='staff status')),
                ('is_active', models.BooleanField(default=True, verbose_name='active')),
                ('is_admin', models.BooleanField(verbose_name='Админ')),
                ('avatar', models.OneToOneField(null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.photos', verbose_name='Аватар')),
                ('current_os', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='os_api.os', verbose_name='Текущая ОС')),
            ],
            options={
                'verbose_name': 'Пользователь',
                'verbose_name_plural': 'Пользователи',
            },
        ),
    ]
