# Generated by Django 3.1.4 on 2021-04-03 13:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0003_auto_20201202_0021'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='username',
            field=models.CharField(default="None", max_length=255, verbose_name='Имя пользователя'),
            preserve_default=False,
        ),
    ]
