# Generated by Django 3.1.4 on 2021-04-03 14:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('os_api', '0011_os_ssh_type'),
        ('core', '0002_auto_20201201_2323'),
        ('user', '0004_user_username'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='avatar',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.photos', verbose_name='Аватар'),
        ),
        migrations.AlterField(
            model_name='user',
            name='current_os',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='os_api.os', verbose_name='Текущая ОС'),
        ),
    ]
